name: ElizaOS Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd project-compliance
          bun install

      - name: Run tests
        run: |
          cd project-compliance
          bun run elizaos test all
